name: Deploy Proxmox K8s Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize Terraform
        run: terraform init -lock=false -input=false

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="proxmox_endpoint=${{ secrets.PROXMOX_ENDPOINT }}" \
            -var="proxmox_user=${{ secrets.PROXMOX_USER }}" \
            -var="proxmox_password=${{ secrets.PROXMOX_PASSWORD }}" \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -var-file="terraform.tfvars" \
            -input=false

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="proxmox_endpoint=${{ secrets.PROXMOX_ENDPOINT }}" \
            -var="proxmox_user=${{ secrets.PROXMOX_USER }}" \
            -var="proxmox_password=${{ secrets.PROXMOX_PASSWORD }}" \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -var-file="terraform.tfvars" \
            -input=false

      - name: Deploy Kubernetes with Kubespray
        working-directory: ./kubespray
        run: |
          source .venv-kubespray/bin/activate
          
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/ansible-key.pem
          chmod 600 /tmp/ansible-key.pem
          
          ansible-playbook cluster.yml \
            -i inventory/k8s-cluster/hosts.ini \
            --become \
            --private-key /tmp/ansible-key.pem \
            -u ubuntu

          rm /tmp/ansible-key.pem